name: Generate Snake Game

on:
  # Runs at midnight UTC every day
  schedule:
    - cron: "0 0 * * *"
  # Allows manual run
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate the snake game from your contributions
      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: shInNei
          outputs: dist/snake.svg

      # Step 2: Commit the output to your repository
      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated snake game"
          branch: main  # Replace with your default branch name
          file_pattern: dist/snake.svg

